LANG = {
    'en': {
        'welcome': "🎉 Welcome, {name}!",
        'join_channel': "You must join our Channel to continue.\n\nAfter joining, click the 'Joined Channel' button below.",
        'join_group': "You must join our Group to continue.\n\nAfter joining, click the 'Joined' button below.",
        'join_group_desc': "After joining the group, click the 'Joined' button below to continue.",
        'not_joined': "❌ You have not joined the {type_label} yet!\n\nPlease join our {type_label} first.",
        'joined_channel': "✅ Thank you! You have successfully joined the channel.",
        'signup_bonus': "🎉 You have received 30 ETB signup bonus.\nYou can withdraw this amount anytime.",
        'valid_referrals': "Valid referrals: {count}",
        'balance': "💰 Balance: {amount} ETB",
        'bonus_unlocked': "Bonus unlocked: {unlocked}",
        'my_earnings': "💰 My Earnings",
        'my_referrals': "🔗 My Referrals",
        'withdraw': "📤 Withdraw",
        'referral_link': "🔗 Referral Link",
        'leaderboard': "🏆 Leaderboard",
        'history': "📜 History",
        'settings': "⚙️ Settings",
        'language': "🌐 Language",
        'select_language': "🌐 Select your language:",
        'english': "English",
        'amharic': "Amharic",
        'back_home': "⬅️ Back to Home",
        'withdraw_how_much': "How much do you want to Withdraw?",
        'withdraw_minmax': "<pre>Here are the minimum and maximum amount you can withdraw,\nMinimum Amount: 30 ETB\nMaximum Amount: 1,000 ETB</pre>",
        'withdraw_invalid': "❌ Please enter a valid number.",
        'withdraw_min': "❌ Minimum withdraw amount is 30 ETB.",
        'withdraw_max': "❌ You cannot withdraw more than your balance ({balance} ETB).",
        'withdraw_eligibility_error': "❌ You must send a referral to at least 10 people to withdraw the money, the minimum withdrawal is 30 Birr.",
        'withdraw_enter_phone': "Please enter your NanaBet account phone number.",
        'withdraw_enter_id': "Please enter your NanaBet ID.",
        'withdraw_confirm': "Please confirm your withdrawal:\n\n<pre>Phone: {phone}\nNanaBet ID: {nana_id}\nRequested Amount: {amount} ETB\nTransaction Fee: {fee} ETB\nYou will receive: {net} ETB</pre>",
        'withdraw_success': "✅ Your withdrawal request has been submitted! (Admin will process it soon.)",
        'withdraw_cancelled': "❌ Withdrawal cancelled.",
        'withdraw_cancel': "Cancel",
        'withdraw_confirm_btn': "Confirm",
        'total_earned': "💸 Total Earned",
        'locked_bonus': "🔓 Locked Bonus",
        'available_balance': "🧾 Available Balance",
        'total_referred_users': "👥 Total Referred Users",
        'referred_today': "🧮 Referred Today",
        'next_target': "📌 Status",
        'invite_now': "🚀 Share this link with your friends:",
        'view_subscription_status': "👁 View Subscription Status Again",
        'rules': "📚 Rules and Regulations",
        'faq': "❓ FAQ / Help",
        'channel': "Channel",
        'group': "Group",
        'more_to_unlock': 'referrals completed',
        'unlocked': 'Unlocked!',
        'no_referrals': 'No referrals yet.',
        'top_referrers': '🏆 Top 10 Referrers:',
        'referrals': 'referrals',
        'no_withdrawal_history': 'No withdrawal history found.',
        'last_withdrawals': '💸 Last Withdrawals:',
        'rules_text': '📚 How to Earn Money:\n1. Join our channel and group.\n2. You receive 30 ETB signup bonus.\n3. Refer 10 people to unlock your bonus.\n4. For each referral after 10, you earn 2.5 ETB.\n5. You can withdraw when you have at least 30 ETB.',
        'faq_text': '❓ FAQ / Help:\n- How do I get my bonus?\n  → You receive 30 ETB signup bonus automatically.\n- How do I withdraw?\n  → You can withdraw your bonus anytime.\n- Who can I contact for support?\n  → Contact the admin @nanabet1.',
        'admin_withdrawals_title': '🛡 Pending Withdrawals',
        'admin_no_withdrawals': 'No pending withdrawals.',
        'admin_withdraw_approve': '✅ Approve',
        'admin_withdraw_reject': '❌ Reject',
        'admin_withdraw_approved': '✅ Withdrawal approved and user notified.',
        'admin_withdraw_rejected': '❌ Withdrawal rejected and user notified.',
        'admin_withdraw_user_approved': '✅ Your withdrawal has been approved! You will receive your money soon.',
        'admin_withdraw_user_rejected': '❌ Your withdrawal request has been rejected. Please contact support if you have questions.',
        'admin_only': 'This command is for admin only.',
        'admin_no_approved_withdrawals': 'No approved withdrawals found.',
        'admin_panel_title': '🛡 Admin Panel',
        'admin_panel_withdrawals': 'View pending withdrawals',
        'admin_panel_approved': 'View approved withdrawals',
        'admin_panel_export': 'Export all users to Excel',
        'promo_message': "💰Earn money from home with Nana Bet Referral! 💵\n\n⭕️Join this bot and just by sharing with people, earn over 1000 Birr per day, plus win 1 iPhone 16 Pro Max from our daily 5 phone draws.\n\n🔗Referral Link:",
        'invalid_command': "❌ Invalid command. Use /start to begin or check the menu for available commands.",
        'cmd_start_restart': "🔄 Start - Restart",
        'cmd_referral': "🔗 Referral",
        'welcome_new': "✅ Welcome to the bot!\n\n🎉 You have received a 30 ETB signup bonus.\n\n💰 Balance: {balance}\nWithdraw: {can_withdraw}",
    },
    'am': {
        'welcome': "🎉 እንኳን ደህና መጡ, {name}!",
        'join_channel': "ለመቀጠል ቻናላችንን ይቀላቀሉ።\n\nከተቀላቀሉ በኋላ 'Joined Channel' ቁልፍ ይጫኑ።",
        'join_group': "ለመቀጠል ግሩፓችንን ይቀላቀሉ።\n\nከተቀላቀሉ በኋላ 'Joined' ቁልፍ ይጫኑ።",
        'join_group_desc': "ግሩፑን ከተቀላቀሉ በኋላ 'Joined' ቁልፍ ይጫኑ።",
        'not_joined': "❌ አሁንም {type_label} አልቀላቀሉም!\n\nእባክዎን መጀመሪያ {type_label} ይቀላቀሉ።",
        'joined_channel': "✅ አመሰግናለሁ! ቻናሉን በትክክል ቀላቀሉ።",
        'signup_bonus': "🎉 30 ብር የመመዝገቢያ ብቃት ተሰጥቷል።\nይህን ብር ያንድ ጊዜ ማውጣት ይችላሉ።",
        'valid_referrals': "ትክክለኛ ሪፈራል: {count}",
        'balance': "💰 ቀሪ ሂሳብ: {amount} ብር",
        'bonus_unlocked': "ብቃት ተከፍቷል: {unlocked}",
        'my_earnings': "💰 የኔ ገቢ",
        'my_referrals': "🔗 የኔ ሪፈራል",
        'withdraw': "📤 ወጪ",
        'referral_link': "🔗 ሪፈራል ሊንክ",
        'leaderboard': "🏆 አሸናፊዎች",
        'history': "📜 ታሪክ",
        'settings': "⚙️ ቅንብሮች",
        'language': "🌐 ቋንቋ",
        'select_language': "🌐 ቋንቋዎን ይምረጡ:",
        'english': "እንግሊዝኛ",
        'amharic': "አማርኛ",
        'back_home': "⬅️ ወደ መነሻ",
        'withdraw_how_much': "ምን መጠን ማውጣት ይፈልጋሉ?",
        'withdraw_minmax': "<pre>ከፍተኛና ዝቅተኛ የማውጣት መጠን፣\nዝቅተኛ: 30 ብር\nከፍተኛ: 1,000 ብር</pre>",
        'withdraw_invalid': "❌ እባክዎን ትክክለኛ ቁጥር ያስገቡ።",
        'withdraw_min': "❌ ዝቅተኛ የማውጣት መጠን 30 ብር ነው።",
        'withdraw_max': "❌ ከቀሪ ሂሳብዎ ({balance} ብር) በላይ ማውጣት አይችሉም።",
        'withdraw_eligibility_error': "❌ ገንዘብ ለማውጣት ቢያንስ 10 ሰዎችን በሪፈራል ማስላላት አለብዎት፣ ዝቅተኛ የማውጣት መጠን 30 ብር ነው።",
        'withdraw_enter_phone': "እባክዎን የNanaBet የመለያ ስልክ ቁጥርዎን ያስገቡ።",
        'withdraw_enter_id': "እባክዎን የNanaBet IDዎን ያስገቡ።",
        'withdraw_confirm': "እባክዎን ውጪዎን ያረጋግጡ:\n\n<pre>ስልክ: {phone}\nNanaBet ID: {nana_id}\nየተጠየቀ መጠን: {amount} ብር\nክፍያ: {fee} ብር\nየሚደርስዎት: {net} ብር</pre>",
        'withdraw_success': "✅ የውጪ ጥያቄዎ ተሳክቷል! (አስተዳዳሪ በቅርቡ ይሰራው)",
        'withdraw_cancelled': "❌ ውጪ ተሰርዟል።",
        'withdraw_cancel': "ሰርዝ",
        'withdraw_confirm_btn': "አረጋግጥ",
        'total_earned': "💸 ጠቅላላ ገቢ",
        'locked_bonus': "🔓 የተዘጋጀ ብቃት",
        'available_balance': "🧾 የቀሪ ሂሳብ",
        'total_referred_users': "👥 ጠቅላላ የተጋበዙ ተጠቃሚዎች",
        'referred_today': "🧮 ዛሬ የተጋበዙ",
        'next_target': "📌 ሁኔታ",
        'invite_now': "🚀 ይህን ሊንክ ከጓደኞቻችሁ ጋር ያጋሩ:",
        'view_subscription_status': "👁 የተመዘገበውን ሁኔታ ደግመው ይመልከቱ",
        'rules': "📚 አሰራራ እና ህጎች",
        'faq': "❓ የተደጋጋሚ ጥያቄዎች / እርዳታ",
        'channel': "ቻናል",
        'group': "ግሩፕ",
        'more_to_unlock': 'ሪፈራል ተጠናቅቋል',
        'unlocked': 'ተከፍቷል!',
        'no_referrals': 'ምንም ሪፈራል አልተገኘም።',
        'top_referrers': '🏆 ከፍተኛ 10 ሪፈራል አሸናፊዎች:',
        'referrals': 'ሪፈራል',
        'no_withdrawal_history': 'የውጪ ታሪክ አልተገኘም።',
        'last_withdrawals': '💸 የቅርብ ውጪዎች:',
        'rules_text': '📚 ብር እንዴት እንደሚሰራ:\n1. ቻናልና ግሩፕ ይቀላቀሉ።\n2. 30 ብር የመመዝገቢያ ሽልማት ይሸለማሉ።\n3. 10 ሰዎችን ሪፈራል ማድረግ ለብቃት መክፈት አለብዎት።\n4. ከ10 በኋላ ለእያንዳንዱ ሪፈራል 2.5 ብር ይገኛሉ።\n5. ቢያንስ 30 ብር ሲኖርዎ ብር ማውጣት ይችላሉ።',
        'faq_text': '❓ የተደጋጋሚ ጥያቄዎች / እርዳታ:\n- ብር እንዴት እገኛለሁ?\n  → 30 ብር የመመዝገቢያ ሽልማት በራስ ሰር ይሸለማሉ።\n- ብር እንዴት እሰራለሁ?\n  → የሽልማት ብርዎን ያንድ ጊዜ ማውጣት ይችላሉ።\n- የድጋፍ ሰው ማን ነው?\n  → አስተዳዳሪን ያግኙ @nanabet1 ።',
        'admin_withdrawals_title': '🛡 በመጠባበቅ ያሉ ውጪዎች',
        'admin_no_withdrawals': 'በመጠባበቅ ያለ ውጪ የለም።',
        'admin_withdraw_approve': '✅ አረጋግጥ',
        'admin_withdraw_reject': '❌ አትችልም',
        'admin_withdraw_approved': '✅ ውጪ ተረጋግጧል እና ተጠቃሚው ተነግሯል።',
        'admin_withdraw_rejected': '❌ ውጪ ተቀባይነት አላገኘም እና ተጠቃሚው ተነግሯል።',
        'admin_withdraw_user_approved': '✅ የውጪዎ ጥያቄ ተረጋግጧል! በቅርቡ ገንዘብዎን ይቀበሉ።',
        'admin_withdraw_user_rejected': '❌ የውጪዎ ጥያቄ ተቀባይነት አላገኘም። ጥያቄ ካለዎት አገልግሎት ያግኙ።',
        'admin_only': 'ይህ ትእዛዝ ለአስተዳዳሪ ብቻ ነው።',
        'admin_no_approved_withdrawals': 'የተፈቀዱ ውጪዎች አልተገኙም።',
        'admin_panel_title': '🛡 አስተዳዳሪ ፓነል',
        'admin_panel_withdrawals': 'በመጠባበቅ ያሉ ውጪዎችን ይመልከቱ',
        'admin_panel_approved': 'የተፈቀዱ ውጪዎችን ይመልከቱ',
        'admin_panel_export': 'ሁሉንም ተጠቃሚዎች ወደ Excel ያስመጡ',
        'promo_message': "💰በናና ቤት ሪፈራል ከቤቶ ሆነው ገንዘብ ይስሩ! 💵\n\n⭕️ይህን ቦት ተቀላቅለው ለሰው በማስተላለፍ ብቻ በቀን ከ1000 ብር በላይ ይስሩ ፣ በተጨማሪም በየቀኑ ከምንሸልማቸው 5 Iphone 16 Pro Max ስልኮች 1 ይሸለሙ።\n\n🔗የሪፈራል ሊንክ፡",
        'invalid_command': "❌ ትክክለኛ ትእዛዝ አይደለም። ለመጀመር /start ይጠቀሙ ወይም የሚያገለግል ትእዛዝ ለማየት ምናሌ ይመልከቱ።",
        'cmd_start_restart': "🔄 ጀምር - ዳግም ጀምር",
        'cmd_referral': "🔗 ሪፈራል",
        'welcome_new': "✅ እንኳን ወደናና ቤት ሪፈራል በሰላም መጡ\n\n🎉 30 ብር የመመዝገቢያ ሽልማት አለዎት\n\n💰 ሂሳቦ: {balance}\nማውጣት ይችላሉ: {can_withdraw}",
    }
} 